#!/usr/bin/env bash
# write a Bash script that will display information about subdomains.

# Define function to display DNS record information
display_dns_record() {
  local domain="$1"
  local subdomain="$2"
  local record_type="$3"
  local destination="$4"
  echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

# Check if the domain argument is provided
if [[ -z "$1" ]]; then
  echo "Error: Domain argument is missing"
  exit 1
else
  DOMAIN="$1"
fi

# Check if the subdomain argument is provided
if [[ -z "$2" ]]; then
  SUBDOMAINS=("www" "lb-01" "web-01" "web-02")
else
  SUBDOMAINS=("$2")
fi

# Loop through each subdomain and display its DNS record information
for SUBDOMAIN in "${SUBDOMAINS[@]}"; do
  RECORD=$(dig "$SUBDOMAIN.$DOMAIN" +short | awk 'NR==1')
  display_dns_record "$DOMAIN" "$SUBDOMAIN" "A" "$RECORD"
done
