#!/usr/bin/env bash

# Check if the domain argument is provided
if [[ -z "$1" ]]; then
  echo "Error: Domain argument is missing"
  exit 1
else
  DOMAIN="$1"
fi

# Check if the subdomain argument is provided
if [[ -z "$2" ]]; then
  SUBDOMAINS=("www" "lb-01" "web-01" "web-02")
else
  SUBDOMAINS=("$2")
fi

# Loop through each subdomain and display its DNS record information
for SUBDOMAIN in "${SUBDOMAINS[@]}"; do
  RECORD=$(nslookup "$SUBDOMAIN.$DOMAIN" | awk '/^'$SUBDOMAIN'/ {print $NF}')
  TYPE=$(echo "$RECORD" | awk -F ' ' '{print $1}')
  DESTINATION=$(echo "$RECORD" | awk -F ' ' '{print $NF}')
  echo "The subdomain $SUBDOMAIN is a $TYPE record and points to $DESTINATION"
done
