#!/usr/bin/env bash
# 404 error page

echo "Ceci n'est pas une page" | sudo tee /var/www/html/error404.html
sudo sed -i '/server_name _;/a\\terror_page 404 /error404.html;' /etc/nginx/sites-available/default
sudo service nginx restart