#!/usr/bin/env bash
# a Bash script that generates a MySQL dump and creates a compressed archive out of it.
mysqldump -u root --password="$1" -A --events > backup.sql
compressed=$(date +"%d-%m-%Y")
tar -czvf "$compressed".tar.gz backup.sql
