#!/usr/bin/env bash
# SIGTERM SIGINT SIGQUIT

trap 'echo "I hate the kill command"; rm -f /var/run/myscript.pid; exit 0' SIGTERM
trap 'echo "Y U no love me?!"; rm -f /var/run/myscript.pid; exit 0' SIGQUIT

echo $$ > /var/run/myscript.pid
while true
do
    echo "To infinity and beyond"
done
