#!/usr/bin/env bash
#use untill loop to print the text 10 times and an if
#to print hi when counter hits 9

counter=0

while [ $counter -lt 10 ]
do
    echo "Best School"
    if [ $counter -eq 8 ]
    then
        echo "Hi"
    fi
    ((counter++))
done
