#!/usr/bin/env bash
#use untill loop to print the text 10 times and an if
#to print hi when counter hits 9

counter=0

while [ $counter -lt 10 ]
do
    if [ $counter -eq 3 ]
    then
        echo "bad luck"
    elif [ $counter -eq 7 ]
    then
	echo "good luck"
    else
	echo "Best School"
    fi
    ((counter++))
done
