#!/usr/bin/env bash
#use untill loop to print the text 20 times and a case statements

counter=1

while [ $counter -lt 21 ]
do
    echo $counter
    case $counter in
	4)
	    echo "bad luck from China"
	    ;;
	9)
	    echo "bad luck from Japan"
	    ;;
	17)
	    echo "bad luck from Italy"
	    ;;
    esac
    ((counter++))
done
