#!/usr/bin/env bash
#printint the clock and its minutres

hour=0
counter=0
while [ $counter -lt 13 ]
do
    echo "Hour: $hour"
    min=1
    while [ $min -lt 60 ]
    do
	echo "$min"
	((min++))
    done
    ((hour++))
    ((counter++))
done
