#!/usr/bin/env bash
#file operations

if [ -e school ];
then
    echo "school file exists"
    if [ -s school ];
    then
	echo "school file is not empty"
    else
	echo "school file is empty"
    fi

    if [ -f school ];
    then
	echo "school file is a regular file"
    fi
else
    echo "school file doesn't exist"
fi
