#!/usr/bin/env bash
# a Bash script that configures the container to fit the requirements
sudo service nginx stop 2&> /dev/null
service apache2 stop 2&> /dev/null
pkill apache2
chmod 644 /etc/nginx/nginx.conf
chown -R nginx /etc/nginx/nginx.conf
su - nginx -c "sed -i -e 's/80/8080/g' /etc/nginx/sites-available/default"
su - nginx -c "service nginx restart" 2&> /dev/null
sudo service nginx start
